#!/bin/bash
echo -n "Adjál meg egy tetszőleges számot: "
read a
echo -n "Adjál meg egy másik számot is: "
read b
echo "A=$a"
echo "B=$b"
if [ "$a" -eq "$b" ];then
  echo "A két szám egyenlő";
	else
if [ "$a" -gt "$b" ];
then 
	echo "A szám nagyobb, mint B szám";
else 
	echo "B szám nagyobb, mint A szám";
fi;
fi;
